### PR TITLE
Add favicons to layout template

### PR DESCRIPTION
**Pull request by soulcutter**
## Add favicons!
The assets were generated based on a source SVG that is not redistributable.

Icon sizes and declarations were generated using
https://realfavicongenerator.net/

### Contribution Notes

The CONTRIBUTING.md file indicates tests can be run using `bundle exec sus` however `sus` is not in the `Gemfile` and therefore this command is not found.

The CONTRIBUTING.md file indicates files should be linted using `bundle exec rubocop -A` however `rubocop` is not in the `Gemfile` and therefore this command is not found.

### CODE REVIEW

**Comment by joeldrapper** [comment]
Thank you! Can I send you the SVG for the graphics? I’m not allowed to publish it due to licencing but I could send a copy by email.

**Comment by soulcutter** [comment]
Sure. [my githubname]@(my github name) . com is good (Sorry for the obfuscation)

**Comment by soulcutter** [comment]
It's also fine if you want to generate them yourself and make the adjustments to this PR. I can understand needing to be careful about licensing.

**Comment by joeldrapper** [comment]
I just sent you the SVG by email. 🙏

**Comment by soulcutter** [comment]
@joeldrapper This now has the final versions of assets and manifests and favicon declarations and such. I think it's good!

**Pull request merged**
